// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { SideNav } from "./side-nav";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-8 min-h-screen px-4">
      <div className="flex flex-col md:flex-row gap-6">
        <SideNav />
        <div className="w-full min-w-0">{children}</div>
      </div>
    </main>
  );
}
